name: simple_ecommerc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#/// widget plugins
  cupertino_icons: ^1.0.2
  splash_view: ^2.0.1
  flutter_spinkit: ^5.2.0

#  state management and storage
  get: ^4.6.6
  get_storage: ^2.1.1

# firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf